// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skkfbhktfscvvxangkoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNra2ZiaGt0ZnNjdnZ4YW5na29oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NjcyMDYsImV4cCI6MjA3MzI0MzIwNn0.ExCM_CC1muYWqX-zcSfhxPEer1EJtcnTccC4O7Kgr2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});